import { describe, expect, test } from 'bun:test'
import { createHmac } from 'node:crypto'
import type { TelegramTextRoute } from '../telegram-text-adapter'
import { createTelegramReplyHandle, verifyTelegramReplyHandle } from './reply-handle'
import { parseTelegramReplyArguments } from './telegram-reply-protocol'

describe('Telegram reply handle', () => {
  test('verifies a profile-bound expiring chat/topic route and rejects tampering', () => { const handle = createTelegramReplyHandle('key', { chatId: '-100', messageId: 7, messageThreadId: 9, profile: 'sample-profile', expiresAt: 200 }); expect(verifyTelegramReplyHandle('key', handle, new Set(['-100']), 'sample-profile', 100)).toMatchObject({ chatId: '-100', messageId: 7, messageThreadId: 9 }); expect(() => verifyTelegramReplyHandle('key', handle, new Set(['-100']), 'other-profile', 100)).toThrow('invalid'); expect(() => verifyTelegramReplyHandle('key', handle, new Set(['-100']), 'sample-profile', 201)).toThrow('invalid'); expect(() => verifyTelegramReplyHandle('key', `${handle}x`, new Set(['-100']), 'sample-profile', 100)).toThrow('invalid') })
  test('projects a wide inbound route to a compact bounded reply route', () => { const input: TelegramTextRoute = { id: 'telegram:-100:7', chatId: '-100', chatType: 'supergroup', messageId: 7, messageThreadId: 9, sender: 'operator', timestamp: 1, text: 'x'.repeat(16 * 1024), entities: [{ type: 'bold', offset: 0, length: 1 }], replyText: 'x'.repeat(1024) }; const handle = createTelegramReplyHandle('key', { ...input, profile: 'sample-profile', expiresAt: 200 }); expect(handle.length).toBeLessThanOrEqual(110); expect(verifyTelegramReplyHandle('key', handle, new Set(['-100']), 'sample-profile', 100)).toMatchObject({ chatId: '-100', messageId: 7, messageThreadId: 9 }) })
  test('continues to verify in-flight v1 reply handles', () => { const payload = Buffer.from(JSON.stringify({ v: 1, chatId: '-100', messageId: 7, messageThreadId: 9, profile: 'sample-profile', expiresAt: 200 })).toString('base64url'); const legacy = `${payload}.${createHmac('sha256', 'key').update(payload).digest('base64url')}`; expect(verifyTelegramReplyHandle('key', legacy, new Set(['-100']), 'sample-profile', 100)).toMatchObject({ chatId: '-100', messageId: 7, messageThreadId: 9 }) })
  test('accepts only reply_handle text phase and proxy-supported MarkdownV2', () => { const handle = createTelegramReplyHandle('key', { chatId: '-100', messageId: 7, profile: 'sample-profile', expiresAt: 200 }); expect(parseTelegramReplyArguments({ reply_handle: handle, text: 'ok', phase: 'final', parse_mode: 'MarkdownV2' })).toMatchObject({ phase: 'final', parse_mode: 'MarkdownV2' }); expect(() => parseTelegramReplyArguments({ reply_handle: handle, text: 'bad', phase: 'final', parse_mode: 'HTML' })).toThrow('parse_mode') })
})
