export const MAX_TELEGRAM_REPLY_FRAME_BYTES = 512 * 1024
export const MAX_TELEGRAM_REPLY_RESULT_BYTES = 8 * 1024
export const MAX_TELEGRAM_REPLY_TEXT_CHARACTERS = 16_384
export type TelegramReplyArguments = { reply_handle: string; text: string; phase: 'commentary' | 'final'; parse_mode?: 'MarkdownV2' }
export type TelegramReplyRequest = { version: 1; type: 'reply'; arguments: TelegramReplyArguments }
export type TelegramReplyResponse = { version: 1; ok: true; message_ids: number[] } | { version: 1; ok: false; error: string }
export const TELEGRAM_REPLY_TOOL_SPEC = { name: 'reply', description: 'Send a Telegram commentary update or final response using the reply_handle supplied in the visible channel message.', inputSchema: { type: 'object', properties: { reply_handle: { type: 'string', minLength: 1, maxLength: 512 }, text: { type: 'string', minLength: 1, maxLength: MAX_TELEGRAM_REPLY_TEXT_CHARACTERS }, phase: { type: 'string', enum: ['commentary', 'final'] }, parse_mode: { type: 'string', enum: ['MarkdownV2'] } }, required: ['reply_handle', 'text', 'phase'], additionalProperties: false } } as const
const ARGUMENT_KEYS = new Set(['reply_handle', 'text', 'phase', 'parse_mode']); const REQUEST_KEYS = new Set(['version', 'type', 'arguments'])
export function parseTelegramReplyArguments(value: unknown): TelegramReplyArguments { if (!record(value)) throw new Error('reply arguments must be an object'); exactKeys(value, ARGUMENT_KEYS, 'reply arguments', ['reply_handle', 'text', 'phase']); const reply_handle = bounded(value.reply_handle, 'reply_handle', 512); const text = bounded(value.text, 'text', MAX_TELEGRAM_REPLY_TEXT_CHARACTERS); if (!/^(?:[A-Za-z0-9_-]+|2r(?:\.[A-Za-z0-9_-]+){5})\.[A-Za-z0-9_-]{43}$/u.test(reply_handle)) throw new Error('reply_handle is invalid'); if (value.phase !== 'commentary' && value.phase !== 'final') throw new Error('phase must be commentary or final'); if (value.parse_mode !== undefined && value.parse_mode !== 'MarkdownV2') throw new Error('parse_mode is invalid'); return { reply_handle, text, phase: value.phase, ...(value.parse_mode === undefined ? {} : { parse_mode: value.parse_mode }) } }
export function parseTelegramReplyRequest(raw: string): TelegramReplyRequest { if (utf8Bytes(raw) > MAX_TELEGRAM_REPLY_FRAME_BYTES) throw new Error('Telegram reply frame is too large'); let value: unknown; try { value = JSON.parse(raw) } catch { throw new Error('Telegram reply frame is not valid JSON') }; if (!record(value)) throw new Error('Telegram reply frame must be an object'); exactKeys(value, REQUEST_KEYS, 'Telegram reply frame'); if (value.version !== 1 || value.type !== 'reply') throw new Error('Telegram reply frame has an invalid version or type'); return { version: 1, type: 'reply', arguments: parseTelegramReplyArguments(value.arguments) } }
export function parseTelegramReplyResponse(raw: string): TelegramReplyResponse { if (utf8Bytes(raw) > MAX_TELEGRAM_REPLY_RESULT_BYTES) throw new Error('Telegram reply result is too large'); let value: unknown; try { value = JSON.parse(raw) } catch { throw new Error('Telegram reply result is not valid JSON') }; if (!record(value) || value.version !== 1 || typeof value.ok !== 'boolean') throw new Error('Telegram reply result has an invalid shape'); if (value.ok) { exactKeys(value, new Set(['version', 'ok', 'message_ids']), 'Telegram reply result'); if (!Array.isArray(value.message_ids) || value.message_ids.length === 0 || value.message_ids.length > 17 || value.message_ids.some(item => !Number.isSafeInteger(item) || item < 1)) throw new Error('Telegram reply result has invalid message IDs'); return { version: 1, ok: true, message_ids: [...value.message_ids] as number[] } } exactKeys(value, new Set(['version', 'ok', 'error']), 'Telegram reply result'); return { version: 1, ok: false, error: bounded(value.error, 'Telegram reply error', 1024) } }
export function safeTelegramReplyError(error: unknown): string { const raw = error instanceof Error ? error.message : 'reply rejected'; return Array.from(raw.replace(/[\u0000-\u001f\u007f]+/gu, ' ').replace(/\s+/gu, ' ').trim() || 'reply rejected').slice(0, 1024).join('') }
function bounded(value: unknown, label: string, maxCharacters: number): string { if (typeof value !== 'string' || value.length === 0) throw new Error(`${label} must be a non-empty string`); if (Array.from(value).length > maxCharacters) throw new Error(`${label} exceeds ${maxCharacters} characters`); return value }
function exactKeys(value: Record<string, unknown>, expected: ReadonlySet<string>, label: string, required: string[] = [...expected]): void { if (Object.keys(value).some(key => !expected.has(key)) || required.some(key => !Object.hasOwn(value, key))) throw new Error(`${label} has unknown or missing fields`) }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) }
function utf8Bytes(value: string): number { return new TextEncoder().encode(value).byteLength }
